config/routes.rb
Eats::Application.routes.draw do
  
resources :users
resources :sessions, only: [:new, :create, :destroy]
resources :meals

root  'static_pages#home'
match '/signup',  to: 'users#new',            via: 'get'
match '/signin',  to: 'sessions#new',         via: 'get'
match '/signout', to: 'sessions#destroy',     via: 'delete'
match '/help',    to: 'static_pages#help',    via: 'get'
match '/about',   to: 'static_pages#about',   via: 'get'

  

end

app/models/meal.rb
class Meal < ActiveRecord::Base
	belongs_to :user
	
	default_scope -> { order('created_at DESC') }
	validates :user_id, presence:true
	validates :title, presence:true, length: { maximum: 70}
	validates :content, presence:true, length: { maximum: 500}
	validates :price, presence:true
	validates :mealtype, presence:true
	validates :city, presence: true
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	
	
	
end

app/models/seat.rb
class Seat < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
has_many :meals, dependent: :destroy
before_save { self.email = email.downcase }
before_create :create_remember_token
  
 
 before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  validates :profile, length: { maximum: 500 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
  
  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper



end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
before_action :signed_in_user, only: [:create, :destroy]
before_action :correct_user,   only: :destroy
	


	def create
    @reservation = Reservation.new(reservation_params)
    if @user.save
      sign_in @user
      
      redirect_to @user
    else
      render 'new'
    end
  end

end


    def reservation_params
      params.require(:reservation).permit()
    end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
before_action :signed_in_user, only: [:create, :destroy]
before_action :correct_user,   only: :destroy


def index
  @q = Meal.search(params[:q])
  @meals = @q.result(distinct:true)

end

def new
    @meal = Meal.new

end

def show
    @meal = Meal.find(params[:id])
    @user = @meal.user 
    
 
end



def create

	@meal = current_user.meals.build(meal_params)
    if @meal.save
      
      redirect_to @meal.user
    else
      redirect_to @meal.user
    end

end

def destroy
	@meal.destroy
    redirect_to @meal.user
end

def meal_params
  params.require(:meal).permit(:title, :content, :price, :mealtype, :city)
 end

def correct_user
      @meal = current_user.meals.find_by(id: params[:id])
      redirect_to root_url if @meal.nil?
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end


	def destroy
    sign_out
    redirect_to root_url
	end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@meal = current_user.meals.build if signed_in?
  	
  end

  def help
  end

  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy, :host]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def show
  	@user = User.find(params[:id])
    @meals = @user.meals 
    @meal = current_user.meals.build if signed_in?
    

  end

  def index
    @users = User.all
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  def host
  end



  def new
  	@user = User.new
  end 

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      
      redirect_to @user
    else
      render 'edit'
    end
  end


  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :profile, :password,
                                   :password_confirmation)
    end

    # Before filters



    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
 
  def sign_in(user)
 	  remember_token = User.new_remember_token
 	  cookies.permanent[:remember_token] = remember_token
 	  user.update_attribute(:remember_token, User.encrypt(remember_token))
 	  self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
 	  @current_user = user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end


	def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class ="container">

  	<nav>
    	<ul>

    	</ul>
  	</nav>
  </div>

</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">

      <%= link_to "eatlocal", root_path, id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav navbar-right">
       
        <% if signed_in? %>
        
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">User<b class="fa fa-user fa-fw"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to " My Dashboard  ", current_user, class: "fa fa-home fa-fw" %></li>
            <li><%= link_to " Edit Profile", edit_user_path(current_user), class: "fa fa-pencil fa-fw" %></li>
            <li><%= link_to " Create a Meal", new_meal_path, class: "fa fa-pencil fa-fw" %></li>
            <li class="divider"></li>
            <li> <%= link_to " Sign out", signout_path, class: "fa fa-ban fa-fw",method: "delete" %></li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "SIGN UP",    signup_path %></li>
        <li><%= link_to "LOGIN",          signin_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_shim.html.erb
 <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <title> Eats | <%= yield(:title) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
   
  </head>
  <body>

    <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %>
        </div>
    <% end %>
    </div>


  <%= yield %> 

   

   <%= render 'layouts/footer' %>

  </body>
</html>

app/views/meals/_meal.html.erb
    <div class="col-sm-4 col-md-4">  
      <div class= "thumbnail center">
          <%= image_tag  ("Background.jpg")%> 
       
      </div>
    
     
      <div class = "mealthumbnails"> 
       
        
      <h1><%= meal.title%></h1>
      <p><%= meal.content %></p>
      <p> By: <%=link_to meal.user[:name], meal %> | <%= meal.city %> </p>
    <p><%= meal.price %></p>
    
      </div>

  </div>
	  


      
  

app/views/meals/index.html.erb
<% provide(:title, 'All Meals') %>
<div class = "container">

	<%= render @meals %>

</div>








 


    
   

app/views/meals/new.html.erb
<div class = "main">
<div class="container" >
      <h1>
      Create a Meal
      </h1>
     
        
        <p>
        

      </p>


 <%= render 'shared/meal_form' %> 

</div>
</div>

app/views/meals/show.html.erb
<div class = "main">
<div class= "container" >


<h4> <%= @meal.title %> </h4>
<%= @meal.content %>
<br>
Price: $<%= @meal.price %>
<br>
By: <%= link_to @meal.user[:name], @user %>
</div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_meal_form.html.erb
<%= form_for(@meal) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

   <h2> Title 
    <%= f.text_field :title, placeholder: "e.g. 'Pasta Party Bologna Style.'" %>
    Your Menu
		<%= f.text_area :content, size: "30x6", placeholder: "eg. 'My meal consists of three courses. First it starts with bacon wrapped dates that are stuffed with goat cheese. Following the appetizer with the main cource I will serve spicy strips of chicken in a delicious sauce consisting of cream, garlic, pepper, butter, and Parmesan cheese served on a bed of fettuccine, with a side salad. Finally for dessert, I have prepared a simple chocolate gelato.'" %>
		Price Per Person 
		<%= f.number_field :price, placeholder:"Number only. eg '20'"%>
		Meal Type
		<%= f.select(:mealtype, [['Dinner'], ['Brunch']])%>
    City Type
    <%= f.select(:city, [['New York'], ['Seattle']])%>

  <%= f.submit "Create Meal", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_thumbnail.html.erb
<div class = "thumbnail" <div>
	<%= image_tag "brunch.jpg" %>

</div>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %> 

<div class="jumbotron">
  <div class="container">
    <div class = "overlay_home">
      <h1> Dine Right. </h1>
		  <h2> Find hosts who will prepare you a home cooked meal. </h2>
      <div class="center">
      <a href = "/meals" class="btn btn-primary large">Show me meals </a>
      </div>
    </div>   
  </div>
</div>

<div class = "bannerone">
  <div class="container">




   
  </div>
</div>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "Are you sure you want to delete this user?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<div class = "main">

<div class="container">

  <div class="col-sm-12 col-md-6 col-md-offset-3">  
    
    
    <div class = "signupform center">
<h1><center>UPDATE MY INFORMATION</center></h1>
  
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <br>
      <%= f.text_field :name %>
      <br>

      <%= f.label :email %>
      <br>
      <%= f.text_field :email %>
      <br>

      <%= f.label :profile %>
      <br>
      <%= f.text_field :profile %>
      <br>

      <%= f.label :password %>
      <br>
      <%= f.password_field :password %>
      <br>


      <%= f.label :password_confirmation, "Confirm Password" %>
      <br>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

</div>
</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>

<div class = "main">
<div class="container">
<h1>All users</h1>

<ul class="users">
	<%= render @users %>
</ul>

</div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class = "container">
  <div class="col-sm-12 col-md-6 col-md-offset-3">  
    
    
    <div class = "signupform center">
      <p style="background-color:#D6F0FF;">Already have an account? Skip the line and <a href =  "/signin"> sign in here. </a> </p>
    <h1><center>READY TO START EATING?<center></h1>
    <p> Easily sign up by providing just your name and email. <br>You can fill out your profile in more detail later. </p>
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

     
      <br>
      <%= f.text_field :name, placeholder: " First Name" %>
      <br>
    
      <br>
      <%= f.text_field :email, placeholder: " Email"%>
      <br>
     
      <br>
      <%= f.password_field :password, placeholder: " Password" %>
      <br>  
      
      <br>
      <%= f.password_field :password_confirmation, placeholder: " Confirm Password" %>
      <br>
      <%= f.submit "Join Now", class: "btn btn-large btn-primary" %>
    <% end %>
    </div>
  </div>

</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>


<div class= "container" >
  <div class = "col-12">
      <h1>  <%= @user.name %>
                              
     <% if @user.profile? %> </h1>
          
        <p>  <%= @user.profile%> </p>
          <% end %>
  </div>  
      
     

         

 <% if @user.meals.any? %>


    
    <% @meals.each do |meal| %>
    <div class = "row">
    <div class="col-md-6">
      <div class = "thumbnail">
     
        <h4><%=link_to meal.title, meal %></h4>
        <p> By: <%=meal.user[:name] %> | <%= meal.city %> 

   Price Per Person: $<%= meal.price %><br><br>
      
  
  <% if current_user?(meal.user) %>

    <%= link_to " Delete", meal, class: "fa fa-trash-o fa-sm", method: :delete,
                                     data: { confirm: "You sure?" },
                                     ohboy: meal.title %>


  <% end %>
</p>


      </div>
   
  </div>
    <% end %>



    



 

      

      
    	<% end %>
   
<% render @meals %>

</div>
</div>
</div>
</div>